### ISSUE TITLE
Function to delete node from given bst

### ISSUE THREAD

**Issue by mradulrathore** [mradulrathore/InterviewQuestions#1]
Leetcode question: Delete Node in a BST
Given a root node reference of a BST and a key, delete the node with the given key in the BST. Return the root node reference (possibly updated) of the BST.
Input: root = [5,3,6,2,4,null,7], key = 3
Output: [5,4,6,2,null,null,7]

**Comment by mahakmandlecha** [comment]
I'm working on it.
