### ISSUE TITLE
Range Sum Query - Mutable

### ISSUE THREAD

**Issue by mradulrathore** [mradulrathore/InterviewQuestions#15]
Given an integer array nums, find the sum of the elements between indices i and j (i ≤ j), inclusive.

The update(i, val) function modifies nums by updating the element at index i to val.

Given nums = [1, 3, 5]

sumRange(0, 2) -> 9
update(1, 2)
sumRange(0, 2) -> 8

Constraints:

The array is only modifiable by the update function.
You may assume the number of calls to update and sumRange function is distributed evenly.
0 <= i <= j <= nums.length - 1

**Comment by MannarAmuthan** [comment]
Hi, Could I do pull request for this task?
