### ISSUE TITLE
The kth Factor of n

### ISSUE THREAD

**Issue by mradulrathore** [mradulrathore/InterviewQuestions#3]
Leetcode Question
Given two positive integers n and k.

A factor of an integer n is defined as an integer i where n % i == 0.

Consider a list of all factors of n sorted in ascending order, return the kth factor in this list or return -1 if n has less than k factors.

Input: n = 12, k = 3
Output: 3
Explanation: Factors list is [1, 2, 3, 4, 6, 12], the 3rd factor is 3.

**Comment by stevenbudinata** [comment]
I'd like to work on this, thank you

**Comment by rtvksingh** [comment]
can i work on this??
