### ISSUE TITLE
Find Peak Element

### ISSUE THREAD

**Issue by mradulrathore** [mradulrathore/InterviewQuestions#7]
A peak element is an element that is greater than its neighbors.

Given an input array nums, where nums[i] ≠ nums[i+1], find a peak element and return its index.

The array may contain multiple peaks, in that case return the index to any one of the peaks is fine.

You may imagine that nums[-1] = nums[n] = -∞.

Input: nums = [1,2,3,1]
Output: 2
Explanation: 3 is a peak element and your function should return the index number 2.

**Comment by rtvksingh** [comment]
can i work on this??

**Comment by mahakmandlecha** [comment]
Can I take this??
